
# Force dep to vendor the code generators, which aren't imported just used at dev time.
# Picking a subpackage with Go code won't be necessary once https://github.com/golang/dep/pull/1545 is merged.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/openshift/library-go/cmd/crd-schema-gen",
]

[[override]]
  name = "k8s.io/code-generator"
  source = "https://github.com/openshift/kubernetes-code-generator.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "k8s.io/api"
  source = "https://github.com/openshift/kubernetes-api.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  source = "https://github.com/openshift/kubernetes-apiextensions-apiserver.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "k8s.io/apimachinery"
  source = "https://github.com/openshift/kubernetes-apimachinery.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "k8s.io/client-go"
  source = "https://github.com/openshift/kubernetes-client-go.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  source = "https://github.com/openshift/kubernetes-sigs-controller-tools.git"
  branch = "origin-4.0-kubernetes-1.12.4"

[[override]]
  name = "github.com/openshift/client-go"
  revision = "0255926f53935175fe90b8e7672c4c06c17d79e6"

[[override]]
  name = "github.com/openshift/api"
  revision = "77b8897ec79a562e85920134fc65b63300c4d27a"

[[override]]
  name = "github.com/openshift/library-go"
  revision = "160e3e0c53fc0b0d707ba97cb09ea490119b1257"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.90"

[[constraint]]
  branch = "master"
  name = "github.com/openshift/installer"
